### ISSUE TITLE
Jumping to an date does not work as long as the page scrolling is still happening

### ISSUE THREAD

**Issue by niklashomann** [JonasWanke/timetable#135]
First, thank you very much for your great package!

We have encountered an issue where we cannnot jump to an specific date (using the DateController) as long as the calendar is still scrolling horizontally. While this is already slightly problematic, this leads to another problem when the target date (the date we jump to) is far away from the current shown days. Then the height of the header for the current shown days gets invalidated (because for a short moment, the target date is the selected date) but it does not really change the date and the header height is not recalculated again for the current visible days.

Here is a video of the bug, the button at the top jumps to the current day.

https://user-images.githubusercontent.com/76853529/213460753-409eb269-2d16-4bfc-9e43-0aaf5eb384c6.mp4

**Comment by JonasWanke** [comment]
This is fixed as part of [v1.0.0-alpha.11](https://pub.dev/packages/timetable/versions/1.0.0-alpha.11/changelog#100-alpha11--2023-01-24)

**Comment by niklashomann** [comment]
I have just updated my dependency, but sadly this problem still persist.
